services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - /usr/src/app/node_modules
      - profile_pictures:/usr/src/app/uploads
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./area.sql:/docker-entrypoint-initdb.d/area.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  profile_pictures:
  pgdata:
