services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - /usr/src/app/node_modules
      - profile_pictures:/usr/src/app/uploads
    depends_on:
      - db
    command: npm run dev

  client_mobile:
    build:
      context: ./mobile
    ports:
      - "8082:8082"
    volumes:
      - shared_mobile_web:/app/dist
      - ./mobile:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    network_mode: "host"

  client_web:
    build:
      context: ./web
    ports:
      - "8081:8081"
    volumes:
      - shared_mobile_web:/app/dist
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - client_mobile
      - server

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./area.sql:/docker-entrypoint-initdb.d/area.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  profile_pictures:
  shared_mobile_web:
  server_node_modules:
  pgdata:
