name: Format & Lint (mobile)

on:
  pull_request:
    paths:
      - "mobile/**"

jobs:
  format:
    if: github.repository != 'EpitechPGE3-2025/G-DEV-500-NAN-5-1-area-2'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: mobile/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier (check mode)
        run: npx prettier . --write

  lint:
    if: github.repository != 'EpitechPGE3-2025/G-DEV-500-NAN-5-1-area-2'
    needs: format
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: mobile/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier (check mode)
        run: npx prettier --check .
