name: Require dev as source

on:
  pull_request:
    branches: [ main ]

jobs:
  check-source:
    runs-on: ubuntu-latest
    steps:
      - name: Verify base branch
        run: |
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "❌ Only PRs from 'dev' can be merged into 'main'."
            exit 1
          fi
